### ISSUE TITLE
Use of uninitialized value in string eq at taparip.pl line 119

### ISSUE THREAD

**Issue by rosecongou** [labster/taparip#4]
All I've changed:

```
my $domain         = 'https://www.tapatalk.com';
my $api_path       = 'groups/veteransblog/viewtopic.php?';
# This is the path of where the database file will be created
# (If you use a relative path, you should keep running it from the same working directory)
my $db_file        = "./veterans.db";
# Select the topics you wish to grab.  The topic ids are part of the URL, like
#     http://domain.yuku.com/hey-guise!-t152-s60.html
# This is topic id 152, starting at post #61
my $start_topic    = 621;
my $end_topic      = 13734;
```

Not really a perl programmer. Not sure what's going on.

**Comment by labster** [comment]
That looks like an error where you didn't even get a error code from the server.  I'm guessing on your end it was this line with the string eq:

>         if ($res->code eq '404') {

So it's not harmful to get that error, but might indicate that the server path is incorrect, or didn't send back a response for some reason.  Did any other pages download okay?

**Comment by labster** [comment]
No response from the issue opener (not surprising given how long I took to respond).  Closing the issue.
